FROM php:7.4.3-apache-buster

ENV APACHE_RUN_USER taskr
ENV APACHE_RUN_GROUP taskr

RUN a2enmod rewrite && \
    # create non-root user
    groupadd --gid 1000 taskr && \
    useradd --uid 1000 --gid taskr --shell /bin/bash --create-home taskr && \
    # install packages
    apt-get update && \
    apt-get -y install \
            curl \
            wget \
            zip \
            unzip \
            nano \
            git \
            libzip-dev \
            default-mysql-client \
            libicu-dev \
            libxml2-dev \
        --no-install-recommends

RUN docker-php-ext-configure bcmath && \
    docker-php-ext-configure zip && \
    docker-php-ext-install \
        zip \
        bcmath \
        exif \
        intl \
        pdo_mysql \
        mysqli \
        pcntl \
        soap

# clear cache
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && mkdir -p /home/taskr/.composer/cache/
# install nodejs
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash && apt-get install -y nodejs

RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini

ADD ./000-default.conf /etc/apache2/sites-available/000-default.conf
ADD ./dev/docker-php-ext-app.ini /usr/local/etc/php/conf.d/docker-php-ext-app.ini

# update folder permissions
RUN chown -R taskr:taskr /var/www/html/
RUN chown -R taskr:taskr /home/taskr/

USER root

WORKDIR /var/www/html/
